### ISSUE TITLE
128版本汉化补丁替换后无法运行程序

### ISSUE THREAD

**Issue by xtp520syy** [tuwulin365/SourceInsight_i18n#2]
大佬，128的汉化补丁替换后弹出版本那个标签后就强制关闭了，进不去主程序呀

**Comment by xtp520syy** [comment]
2.80和2.81都不行

**Comment by tuwulin365** [comment]
注意：
首次运行汉化版，需先删除“我的文档”下的旧的“Source Insight 4.0 chs”文件夹，否则可能无法显示菜单栏菜单。
后续再更新汉化补丁，可以先不删除配置。如发现菜单丢失等问题再删除。
删除后原有的配置会清空，需要重新设置。

删除了没？



***@***.***
 
发件人： xtp520syy
发送时间： 2023-06-10 23:22
收件人： tuwulin365/SourceInsight_i18n
抄送： Subscribed
主题： Re: [tuwulin365/SourceInsight_i18n] 128版本汉化补丁替换后无法运行程序 (Issue #2)
2.80和2.81都不行
