### ISSUE TITLE
您好，我用最新版本时有个问题：加载第三方主题xml文件后，整个程序会卡退

### ISSUE THREAD

**Issue by QiHsMing** [tuwulin365/SourceInsight_i18n#4]
您好，我用最新版本时有个问题：加载第三方主题xml文件后，整个程序会卡退！
第三方主题：https://github.com/ultraji/SourceInsightTheme

**Comment by tuwulin365** [comment]
你看我那说明里不是写了不要直接导入主题配置吗，你要手动配置。
