### ISSUE TITLE
这个标签能汉化吗？

### ISSUE THREAD

**Issue by AngusLkc** [tuwulin365/SourceInsight_i18n#6]
虽然看得懂也不影响使用，但是整个软件其他地方都汉化了，就这一个地方看着别扭，风格统一一下多好。
![image](https://github.com/user-attachments/assets/caecd968-a9d2-4616-8a79-a4a571e86ce7)

**Comment by tuwulin365** [comment]
更新了，你试下

**Comment by AngusLkc** [comment]
大佬牛批。
![image](https://github.com/user-attachments/assets/ec94be05-7392-426d-9b58-6da85d0a1bb4)
